# Site settings
title: Jason Wilkin
#twitter_username: N/A
name: Jason Wilkin

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
#- title: Blog
#  url: https://automateddeveloper.blogspot.com/
#- title: GitHub
#  url: https://github.com/robhinds
#- title: StackOverflow
#  url: https://stackoverflow.com/users/258813/rhinds
#- title: DZone
#  url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/jason-wilkin-919066209
#- title: Food
#  url: https://www.robbishfood.com/

#Any buzzword skills you want to include
skills:
 - C#
 - HTML
 - CSS
 - Javascript
 - Typescript
 - Neo4j
 - Mongo DB
 - SQL
 - VBA
 - Microsoft Office
 - REST
 - Data Analytics
 - Test Driven Development 

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Lead Software Developer
   start: 2021
   end: 2021
   employer: Oxford Economics
   location: Full-time: remote
   description: Lead developer on a project to upgrade one of our large steel core business systems that utilises a combination of Neo4j and Mongo databases to import, manipulate and store historical economic data for use in the forecasting process. Updating of all documentation with a hand over of the new completed, tested and deployed system to a new software development team.
 - title: Software Developer
   start: 2018
   end: 2021
   employer: Oxford Economics
   location: Part-time: remote
   description: Continued development of the companies flagship and market leading Global Model Workstation (GMW) desktop software via an agile methodology. Handling of client & staff support issues in line with our companies SLA's. Development of additional GMW component software. Occasional work on the companies new online Model Workstation.
 - title: Software Developer
   start: 2014
   end: 2017
   employer: Oxford Economics
   location: Full-time: remote from August 2015
   description: The development and maintenance of internal and client facing software solutions including the companies flagship and market leading Global Macro Workstation (GMW). This is a desktop system built using a C# backend and a Typescript/Knockout/CSS frontend.
 - title: Software developer (C#/Neo4j)
   start: 2012
   end: 2014
   employer: Oxford Economics
   location: Full-time: Oxford, UK
   description: Development of a large scale data management system using MVC, C#, Neo4j graph database and MongoDb. This system helped to centralise the multiple data sources used within the Oxford Economics core data, reduced bottlenecks upon the Data Team, allowed staff to be more productive, and significantly improved the quality of the data.
 - title: Senior Data Analyst and Software Developer
   start: 2009
   end: 2012
   employer: Oxford Economics
   location: Full-time: Oxford, UK
   description: Responsible for the creation of reports and data processing systems using Microsoft Access/Excel and VBA. Creation, updating and maintenance of large excel data spreadsheets using numerous data sources. Development of the companies data help information database, time sheet and quote systems.   
 - title: Database Developer
   start: 2009
   end: 2009
   employer: Aviva - Contract
   location: Full-time: Norwich, UK
   description: Working for the Operational Support department within Aviva Insurance. I designed and produced an Access database and VBA/Excel based management reporting systems that analysed demand levels within Aviva’s various onshore and offshore call centre’s (11 in total).
• Designed and produced call recording database’s utilising Microsoft Access and VBA.
• Implemented custom validation to ensure accurate data capture.
• Production of dynamic management information reports that were automatically created in Excel via VBA from within a custom built Access based reporting module.
• Production of dynamically created management reporting Flow Charts showing the time and demand analysis statistics for Call demands.
• Automation of control chart creation for the analysis of call times via an advanced multi filtering form utilising dynamic SQL creation and custom array based export module. 

#Education is required
education:
 - level: Higher National Diploma (HND)
   date: 2001
   subject: Business Information Technology
   school: City College Norwich

#This section is optional (as is the image link below)
#coursera:
#   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
#   courses:
#    - title: Functional Programming Principles in Scala
#      link: https://www.coursera.org/course/progfun
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
#      date: September 16, 2013
#    - title: Algorithms Design and Analysis, Part 1
#      link: https://www.coursera.org/specializations/algorithms
#      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
#      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
#github:
# - [Add repo url here]

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: N/A
#   flairimageurl: N/A

intro: |
  I am a full stack Software Engineer with experience in producing both internal and customer facing systems. I have spent the past 12 years working for Oxford Economics Ltd where I held a number of roles and worked across multiple projects utilising the following technologies: Excel, Word, Access Db's, VBA, SQL, MongoDB, Neo4j, HTML, CSS, C#, Javascript, Typescript, MVC and MVVM.
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C#</strong>: In my last role I used C# to build back-end services for a large historical data store. I have also used the C# language when building other applications for Oxford Economics Ltd which also included their flagship client-facing Global Economic Model software. <br/><br/>
   <strong>Neo4j</strong>: I am experienced with Neo4j database creation and developemnt as well as the use of the cypher query language to add, amend, delete and query data. I have been working with a large Neo4j database for the past 9 years as this was our original data store for the Oxford Economics historical data store. More recently In my last role I had experience of migrating legacy Neo4j databases to newer versions and all of the associated cypher query refactoring that was required.<br/><br/>
   <strong>MongoDB</strong> I have experience of using MongoDB within a number of projects within Oxford Economics. The latest instance being in my last role where we decided to split the historical data stores data between 2 database technologies. A Neo4j database was used for all current (active) data while a MongoDB was used for all archived data. <br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with Team Foundation Services (TFS), Git, Jenkins, Appveyor, DevOps etc.<br/><br/>
   I have experience with test driven development (TDD) using a number of technologies within both Javascript and C# as well as automated testing using Selenium to drive browser actions.<br/><br/>
   I have also gained experience and knowledge of other technologies over the past year through online learning and side projects that I have undertaken during my recent career break<br/><br/>
